# learn-ease-fyp/backend/models/ai_schemas.py

from pydantic import BaseModel, Field
from typing import List

class TextForSummarization(BaseModel):
    text_to_summarize: str = Field(..., min_length=10, description="Text selected by the user to be summarized.")

class SummarizationResponse(BaseModel):
    summary: str

# --- Schemas for Flashcard Generation ---
class TextForFlashcards(BaseModel):
    text_to_generate_from: str = Field(..., min_length=10, description="Text selected by the user to generate flashcards from.")

class Flashcard(BaseModel):
    front: str = Field(..., description="The front content of the flashcard (e.g., question or term).")
    back: str = Field(..., description="The back content of the flashcard (e.g., answer or definition).")

class FlashcardsResponse(BaseModel):
    flashcards: List[Flashcard] = Field(..., description="A list of generated flashcards.")

# --- Schemas for Study Notes Generation ---
class TextForStudyNotes(BaseModel):
    text_to_generate_notes_from: str = Field(..., min_length=20, description="Text selected by the user to generate study notes from.")

class StudyNotesResponse(BaseModel):
    study_notes: str = Field(..., description="The generated structured study notes.")

# --- Schemas for Question & Answer Generation ---
class TextForQuestionAnswer(BaseModel):
    text_to_generate_from: str = Field(..., min_length=20, description="Text selected by the user to generate questions and answers from.")

class QuestionAnswerPair(BaseModel):
    question: str = Field(..., description="A generated question from the text.")
    answer: str = Field(..., description="The corresponding answer to the generated question.")

class QuestionAnswerResponse(BaseModel):
    qna_pairs: List[QuestionAnswerPair] = Field(..., description="A list of generated question and answer pairs.")

# --- Schemas for Glossary Generation ---
class TextForGlossary(BaseModel):
    text_to_generate_glossary_from: str = Field(..., min_length=20, description="Text selected by the user to generate a glossary from.")

class GlossaryTerm(BaseModel):
    term: str
    definition: str
    source: str # Will be 'context' or 'general'


# =========================================================================
# --- NEW SCHEMAS FOR QUIZ GENERATION AND EVALUATION (Module 4) ---
# =========================================================================

# 1. Request to generate a quiz from selected content
class QuizGenerationRequest(BaseModel):
    """Schema for the request to generate a quiz."""
    content_text: str = Field(..., min_length=100, description="The content of the topic selected from the book to generate a quiz from.")
    num_questions: int = Field(10, ge=1, le=20, description="Number of questions to generate. Defaults to 10 as per plan.")
    # We will use the standard 'short answer' type as per the plan

# 2. Structure for a single Quiz Question (AI-generated)
class QuizQuestion(BaseModel):
    """Structure of a single question in the generated quiz."""
    question_text: str = Field(..., description="The question generated by the AI.")
    correct_answer: str = Field(..., description="The precise, short AI-generated correct answer.")
    explanation: str = Field(..., description="A brief explanation for the correct answer.")

# 3. The entire Generated Quiz structure (Response to generation request)
class GeneratedQuiz(BaseModel):
    """The complete quiz object returned after generation."""
    quiz_id: str = Field(..., description="A temporary ID for tracking the quiz session (e.g., a hash or UUID).")
    questions: List[QuizQuestion] = Field(..., description="The list of questions and their correct answers.")

# 4. Request for Quiz Evaluation (User's answers)
class UserAnswer(BaseModel):
    """Structure for a single user attempt."""
    question_text: str = Field(..., description="The original question text (for verification).")
    user_answer: str = Field(..., description="The user's short answer attempt.")
    # The index/order might be useful but we'll use question_text for simplicity in the first iteration

class QuizEvaluationRequest(BaseModel):
    """Schema for the user's complete quiz submission for evaluation."""
    quiz_id: str = Field(..., description="The temporary ID of the quiz being evaluated.")
    attempted_answers: List[UserAnswer]
    # --- MODIFICATION: ADDED book_id and topic_name FOR DB STORAGE ---
    book_id: str = Field(..., description="The ID of the book this quiz belongs to.")
    topic_name: str = Field(..., description="The name or identifier of the topic the quiz was for.")

# 5. Structure for a single evaluated question result
class EvaluatedQuestionResult(BaseModel):
    """The result for a single question after evaluation."""
    question_text: str
    user_answer: str
    correct_answer: str
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity between user answer and correct answer.")
    # We will rely on the explanation being in the correct_answer field for now

# 6. Final Quiz Evaluation Response
class QuizEvaluationResponse(BaseModel):
    """The final evaluation and grading response."""
    quiz_id: str
    total_score: float = Field(..., ge=0.0, le=1.0, description="The average similarity score across all questions (0.0 to 1.0).")
    total_grade: str = Field(..., description="A letter grade or qualitative description based on total_score.")
    results: List[EvaluatedQuestionResult]
    
    # Optional field for Progress Tracking Module
    book_id: str | None = Field(None, description="The ID of the book this quiz belongs to, for progress tracking.")