# learn-ease-fyp/backend/models/ai_schemas.py
from pydantic import BaseModel, Field
from typing import List

class TextForSummarization(BaseModel):
    text_to_summarize: str = Field(..., min_length=10, description="Text selected by the user to be summarized.")

class SummarizationResponse(BaseModel):
    summary: str

class TextForFlashcards(BaseModel):
    text_to_generate_from: str = Field(..., min_length=10, description="Text selected by the user to generate flashcards from.")

class Flashcard(BaseModel):
    front: str = Field(..., description="The front content of the flashcard (e.g., question or term).")
    back: str = Field(..., description="The back content of the flashcard (e.g., answer or definition).")

class FlashcardsResponse(BaseModel):
    flashcards: List[Flashcard] = Field(..., description="A list of generated flashcards.")

class TextForStudyNotes(BaseModel):
    text_to_generate_notes_from: str = Field(..., min_length=20, description="Text selected by the user to generate study notes from.")

class StudyNotesResponse(BaseModel):
    study_notes: str = Field(..., description="The generated structured study notes.")

class TextForQuestionAnswer(BaseModel):
    text_to_generate_from: str = Field(..., min_length=20, description="Text selected by the user to generate questions and answers from.")

class QuestionAnswerPair(BaseModel):
    question: str = Field(..., description="A generated question from the text.")
    answer: str = Field(..., description="The corresponding answer to the generated question.")

class QuestionAnswerResponse(BaseModel):
    qna_pairs: List[QuestionAnswerPair] = Field(..., description="A list of generated question and answer pairs.")

class TextForGlossary(BaseModel):
    text_to_generate_glossary_from: str = Field(..., min_length=20, description="Text selected by the user to generate a glossary from.")

class GlossaryTerm(BaseModel):
    term: str
    definition: str
    source: str

class QuizGenerationRequest(BaseModel):
    content_text: str = Field(..., min_length=100, description="The content of the topic selected from the book to generate a quiz from.")
    num_questions: int = Field(10, ge=1, le=20, description="Number of questions to generate. Defaults to 10 as per plan.")

class QuizQuestion(BaseModel):
    question_text: str = Field(..., description="The question generated by the AI.")
    correct_answer: str = Field(..., description="The precise, short AI-generated correct answer.")
    answer_variants: List[str] = Field(..., description="A list of acceptable, alternative answers.") # <-- ADD THIS
    explanation: str = Field(..., description="A brief explanation for the correct answer.")

class GeneratedQuiz(BaseModel):
    quiz_id: str = Field(..., description="A temporary ID for tracking the quiz session (e.g., a hash or UUID).")
    questions: List[QuizQuestion] = Field(..., description="The list of questions and their correct answers.")

class UserAnswer(BaseModel):
    question_text: str = Field(..., description="The original question text (for verification).")
    user_answer: str = Field(..., description="The user's short answer attempt.")

class QuizEvaluationRequest(BaseModel):
    quiz_id: str = Field(..., description="The temporary ID of the quiz being evaluated.")
    attempted_answers: List[UserAnswer]
    book_id: str = Field(..., description="The ID of the book this quiz belongs to.")
    topic_name: str = Field(..., description="The name or identifier of the topic the quiz was for.")

class EvaluatedQuestionResult(BaseModel):
    question_text: str
    user_answer: str
    correct_answer: str
    correct_explanation: str # <-- Keep this one
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity between user answer and correct answer.")

class QuizEvaluationResponse(BaseModel):
    quiz_id: str
    total_score: float = Field(..., ge=0.0, le=1.0, description="The average similarity score across all questions (0.0 to 1.0).")
    total_grade: str = Field(..., description="A letter grade or qualitative description based on total_score.")
    results: List[EvaluatedQuestionResult]
    book_id: str | None = Field(None, description="The ID of the book this quiz belongs to, for progress tracking.")

# =========================================================================
# --- NEW SCHEMAS FOR AI MENTOR CHAT (Module 8) ---
# =========================================================================

class ChatRequest(BaseModel):
    """Schema for a user's chat query."""
    query: str = Field(..., min_length=1, description="The user's question for the AI Mentor.")

class ChatResponse(BaseModel):
    """Schema for the AI Mentor's response."""
    answer: str = Field(..., description="The AI-generated answer based on the book's content.")
    sources: List[str] = Field(..., description="A list of source text chunks used to generate the answer.")