from pydantic import BaseModel, Field
from typing import List, Optional, Literal # <-- Make sure Optional and Literal are imported

class TextForSummarization(BaseModel):
    text_to_summarize: str = Field(..., min_length=10, description="Text selected by the user to be summarized.")

class SummarizationResponse(BaseModel):
    summary: str

class TextForFlashcards(BaseModel):
    text_to_generate_from: str = Field(..., min_length=10, description="Text selected by the user to generate flashcards from.")

class Flashcard(BaseModel):
    front: str = Field(..., description="The front content of the flashcard (e.g., question or term).")
    back: str = Field(..., description="The back content of the flashcard (e.g., answer or definition).")

class FlashcardsResponse(BaseModel):
    flashcards: List[Flashcard] = Field(..., description="A list of generated flashcards.")

class TextForStudyNotes(BaseModel):
    text_to_generate_notes_from: str = Field(..., min_length=20, description="Text selected by the user to generate study notes from.")

class StudyNotesResponse(BaseModel):
    study_notes: str = Field(..., description="The generated structured study notes.")

class TextForQuestionAnswer(BaseModel):
    text_to_generate_from: str = Field(..., min_length=20, description="Text selected by the user to generate questions and answers from.")

class QuestionAnswerPair(BaseModel):
    question: str = Field(..., description="A generated question from the text.")
    answer: str = Field(..., description="The corresponding answer to the generated question.")

class QuestionAnswerResponse(BaseModel):
    qna_pairs: List[QuestionAnswerPair] = Field(..., description="A list of generated question and answer pairs.")

class TextForGlossary(BaseModel):
    text_to_generate_glossary_from: str = Field(..., min_length=20, description="Text selected by the user to generate a glossary from.")

class GlossaryTerm(BaseModel):
    term: str
    definition: str
    source: str

# --- (MODIFIED) This class is now updated ---
class QuizGenerationRequest(BaseModel):
    topic_id: str = Field(..., description="The ID of the BookTopic to generate the quiz from.")
    num_questions: int = Field(10, ge=1, le=20, description="Number of questions to generate. Defaults to 10 as per plan.")
# --- End of modification ---

class QuizQuestion(BaseModel):
    question_text: str = Field(..., description="The question generated by the AI.")
    correct_answer: str = Field(..., description="The precise, short AI-generated correct answer.")
    answer_variants: List[str] = Field(..., description="A list of acceptable, alternative answers.") # <-- ADD THIS
    explanation: str = Field(..., description="A brief explanation for the correct answer.")

class GeneratedQuiz(BaseModel):
    quiz_id: str = Field(..., description="A temporary ID for tracking the quiz session (e.g., a hash or UUID).")
    questions: List[QuizQuestion] = Field(..., description="The list of questions and their correct answers.")

class UserAnswer(BaseModel):
    question_text: str = Field(..., description="The original question text (for verification).")
    user_answer: str = Field(..., description="The user's short answer attempt.")

class QuizEvaluationRequest(BaseModel):
    quiz_id: str = Field(..., description="The temporary ID of the quiz being evaluated.")
    attempted_answers: List[UserAnswer]
    book_id: str = Field(..., description="The ID of the book this quiz belongs to.")
    topic_name: str = Field(..., description="The name or identifier of the topic the quiz was for.")

class EvaluatedQuestionResult(BaseModel):
    question_text: str
    user_answer: str
    correct_answer: str
    correct_explanation: str # <-- Keep this one
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity between user answer and correct answer.")

class QuizEvaluationResponse(BaseModel):
    quiz_id: str
    total_score: float = Field(..., ge=0.0, le=1.0, description="The average similarity score across all questions (0.0 to 1.0).")
    total_grade: str = Field(..., description="A letter grade or qualitative description based on total_score.")
    results: List[EvaluatedQuestionResult]
    book_id: str | None = Field(None, description="The ID of the book this quiz belongs to, for progress tracking.")

# =========================================================================
# --- NEW SCHEMAS FOR AI MENTOR CHAT (Module 8) ---
# =========================================================================

class ChatRequest(BaseModel):
    """Schema for a user's chat query."""
    query: str = Field(..., min_length=1, description="The user's question for the AI Mentor.")

class ChatResponse(BaseModel):
    """Schema for the AI Mentor's response."""
    answer: str = Field(..., description="The AI-generated answer based on the book's content.")
    sources: List[str] = Field(..., description="A list of source text chunks used to generate the answer.")

# =========================================================================
# --- NEW SCHEMAS FOR AI STUDY RECOMMENDATIONS (Module 7) ---
# =========================================================================

RecommendationPriority = Literal["High", "Medium"]

# This defines the "toolbox" of all your app features
RecommendedAction = Literal[
    "AI_MENTOR", 
    "TAKE_QUIZ", 
    "VIEW_SUMMARY", 
    "STUDY_FLASHCARDS", 
    "REVIEW_NOTES", 
    "CHECK_GLOSSARY", 
    "VIEW_QA_PAIRS"
]

class AIStudyRecommendation(BaseModel):
    """
    A single structured recommendation from the LLM.
    """
    priority: RecommendationPriority
    topic_name: str
    score: float = Field(..., description="The average score (0-100)")
    action: RecommendedAction = Field(..., description="The app feature to use")
    recommendation_text: str = Field(..., description="The human-readable text for the user")

class AIRecommendationResponse(BaseModel):
    """
    The full response from the recommendation endpoint, including
    praise for the user's strong topics.
    """
    recommendations: List[AIStudyRecommendation]
    strength_message: Optional[str] = Field(None, description="An encouraging message about the user's strongest topic")

    # (Add this to the end of backend/models/ai_schemas.py)

# =========================================================================
# --- NEW SCHEMAS FOR AI GLOBAL RECOMMENDATIONS (Dashboard) ---
# =========================================================================

GlobalRecommendationAction = Literal[
    "REVIEW_WEAKEST_SUBJECT",
    "PRACTICE_NEW_SUBJECT",
    "VIEW_GLOBAL_PROGRESS",
    "TAKE_ANY_QUIZ"
]

class AIGlobalStudyRecommendation(BaseModel):
    """
    A single high-level recommendation for the global dashboard.
    """
    priority: RecommendationPriority # Re-use this from book recommendations
    action: GlobalRecommendationAction
    title: str = Field(..., description="A short, bold title for the recommendation")
    recommendation_text: str = Field(..., description="The human-readable text for the user")

class AIGlobalRecommendationResponse(BaseModel):
    """
    The full response for the global recommendation endpoint.
    """
    recommendations: List[AIGlobalStudyRecommendation]